//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace AdventureWorks.Core.Domain.Entities
{
    [Table("ProductPhoto", Schema = "Production")]
    public partial class ProductPhoto
    {
        #region Members
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int ProductPhotoId { get; set; }
        public Byte[] LargePhoto { get; set; }
        public string LargePhotoFileName { get; set; }
        public DateTime ModifiedDate { get; set; }
        public Byte[] ThumbNailPhoto { get; set; }
        public string ThumbnailPhotoFileName { get; set; }
        #endregion Members

        #region Equals/GetHashCode
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj))
            {
                return false;
            }
            if (ReferenceEquals(this, obj))
            {
                return true;
            }
            ProductPhoto other = obj as ProductPhoto;
            if (other == null) return false;

            if (LargePhoto != other.LargePhoto)
                return false;
            if (LargePhotoFileName != other.LargePhotoFileName)
                return false;
            if (ModifiedDate != other.ModifiedDate)
                return false;
            if (ThumbNailPhoto != other.ThumbNailPhoto)
                return false;
            if (ThumbnailPhotoFileName != other.ThumbnailPhotoFileName)
                return false;
            return true;
        }
        public override int GetHashCode()
        {
            unchecked
            {
                int hash = 17;
                hash = hash * 23 + (LargePhoto == null ? 0 : LargePhoto.GetHashCode());
                hash = hash * 23 + (LargePhotoFileName == null ? 0 : LargePhotoFileName.GetHashCode());
                hash = hash * 23 + (ModifiedDate == default(DateTime) ? 0 : ModifiedDate.GetHashCode());
                hash = hash * 23 + (ThumbNailPhoto == null ? 0 : ThumbNailPhoto.GetHashCode());
                hash = hash * 23 + (ThumbnailPhotoFileName == null ? 0 : ThumbnailPhotoFileName.GetHashCode());
                return hash;
            }
        }
        public static bool operator ==(ProductPhoto left, ProductPhoto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ProductPhoto left, ProductPhoto right)
        {
            return !Equals(left, right);
        }

        #endregion Equals/GetHashCode
    }
}
